Avoid exposing interactive overrides of AquireTokenAsync in .NET Core
This PR breaks the XForms project. Does it need to be .NET standard 1.1 ?

Severity Code Description Project File Line Suppression State
Error CS1061 'PublicClientApplication' does not contain a definition for 'AcquireTokenAsync' and no extension method 'AcquireTokenAsync' accepting a first argument of type 'PublicClientApplication' could be found (are you missing a using directive or an assembly reference?) XForms C:\gh\adal.net\msal\tests\dev apps\XForms\XForms\AcquirePage.xaml.cs 180 N/A
Error CS1061 'PublicClientApplication' does not contain a definition for 'AcquireTokenAsync' and no extension method 'AcquireTokenAsync' accepting a first argument of type 'PublicClientApplication' could be found (are you missing a using directive or an assembly reference?) XForms C:\gh\adal.net\msal\tests\dev apps\XForms\XForms\AcquirePage.xaml.cs 187 N/A